##section A:Data Structures&control structure

In [1]:
# List operations

numbers = [10, 20, 30, 40, 50]
print("Original List:", numbers)

# append
numbers.append(60)
print("After append:", numbers)

# extend
numbers.extend([70, 80])
print("After extend:", numbers)

# insert
numbers.insert(2, 25)
print("After insert:", numbers)

# remove
numbers.remove(40)
print("After remove:", numbers)

# pop
numbers.pop()
print("After pop:", numbers)

# index
print("Index of 30:", numbers.index(30))

# count
print("Count of 20:", numbers.count(20))

# sort
numbers.sort()
print("After sort:", numbers)

# reverse
numbers.reverse()
print("After reverse:", numbers)

# clear
numbers.clear()
print("After clear:", numbers)

Original List: [10, 20, 30, 40, 50]
After append: [10, 20, 30, 40, 50, 60]
After extend: [10, 20, 30, 40, 50, 60, 70, 80]
After insert: [10, 20, 25, 30, 40, 50, 60, 70, 80]
After remove: [10, 20, 25, 30, 50, 60, 70, 80]
After pop: [10, 20, 25, 30, 50, 60, 70]
Index of 30: 3
Count of 20: 1
After sort: [10, 20, 25, 30, 50, 60, 70]
After reverse: [70, 60, 50, 30, 25, 20, 10]
After clear: []


In [3]:
# Tuple example

students = ("Aditya", "Rahul", "Priya")

# Trying to change second name
students[1] = "Amit"

TypeError: 'tuple' object does not support item assignment

In [ ]:
### Tuples are immutable, meaning their values cannot be changed after creation.

In [4]:
# Set with duplicates

numbers = {1, 2, 3, 4, 4, 5, 5, 6}

print("Set:", numbers)

Set: {1, 2, 3, 4, 5, 6}


In [ ]:
#### Sets automatically remove duplicate values, so each element appears only once.

In [8]:
# Dictionary operations

person = {
    "name": "Aditya",
    "age": 22,
    "city": "Satara"
}

print("Original Dictionary:")
print(person)



Original Dictionary:
{'name': 'Aditya', 'age': 22, 'city': 'Satara'}


In [9]:
person["age"] = 23
person["email"] = "aditya@gmail.com"

print("Updated Dictionary:")
print(person)

Updated Dictionary:
{'name': 'Aditya', 'age': 23, 'city': 'Satara', 'email': 'aditya@gmail.com'}


In [10]:
# Age variable
age = 20

# Check voting eligibility
if age >= 18:
    print("Eligible to vote")
else:
    print("Not eligible to vote")

Eligible to vote


In [14]:
# Marks variable
marks = 78

# Check grade
if marks >= 90:
    print("A")
elif marks >= 75:
    print("B")
elif marks >= 50:
    print("C")
else:
    print("Fail")

B


In [15]:
# Number variable
num = 12

if num > 0:
    print("Positive Number")

    if num % 2 == 0:
        print("Even Number")
    else:
        print("Odd Number")

elif num == 0:
    print("Zero")

else:
    print("Negative Number")

Positive Number
Even Number


### section B:numpy

In [16]:
import numpy as np

scalar = np.array(5)
arr1 = np.array([1,2,3,4,5])
arr2 = np.array([[10,20,30],[40,50,60]])

print(scalar)
print(arr1)
print(arr2)

5
[1 2 3 4 5]
[[10 20 30]
 [40 50 60]]


In [17]:
import numpy as np

# Generate a 4x4 array of random integers between 0 and 100
random_array = np.random.randint(0, 101, size=(4, 4))

print("4x4 Random Array:")
print(random_array)

4x4 Random Array:
[[40 85 99 41]
 [23 70 11 62]
 [75 30 98 15]
 [22  6 35 66]]


In [18]:
import numpy as np
import pandas as pd

# Create a 3x3 NumPy array
arr = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])

# Convert to DataFrame with column names
df = pd.DataFrame(arr, columns=['A', 'B', 'C'])

print(df)

   A  B  C
0  1  2  3
1  4  5  6
2  7  8  9


### Section c:Exploring Pandas

In [19]:
import pandas as pd
import numpy as np

# Create DataFrame
data = {
    "Name": ["Aditya", "Rahul", "Priya", "Sneha", "Amit",
             "Kiran", "Rohit", "Pooja", "Neha", "Aditya"],
    
    "Age": [22, 23, 21, 24, 25,
            22, 23, 24, 21, 22],
    
    "City": ["Satara", "Pune", "Mumbai", "Kolhapur", "Nashik",
             "Pune", "Mumbai", "Satara", "Kolhapur", "Satara"],
    
    "Salary": [30000, 35000, np.nan, 40000, 45000,
               38000, 35000, np.nan, 42000, 30000]
}

df = pd.DataFrame(data)

print("Original DataFrame:")
print(df)

# 1. info()
print("\nDataFrame Info:")
df.info()

# 2. describe()
print("\nDataFrame Description:")
print(df.describe())

# 3. Select Name and City columns
print("\nName and City Columns:")
print(df[["Name", "City"]])

# 4. Drop City column
df_drop = df.drop("City", axis=1)
print("\nAfter Dropping City Column:")
print(df_drop)

# 5. Fill missing Salary values with mean
mean_salary = df["Salary"].mean()
df["Salary"] = df["Salary"].fillna(mean_salary)

print("\nAfter Filling Missing Salary Values:")
print(df)

# 6. Remove duplicate rows
df = df.drop_duplicates()

print("\nAfter Removing Duplicate Rows:")
print(df)

Original DataFrame:
     Name  Age      City   Salary
0  Aditya   22    Satara  30000.0
1   Rahul   23      Pune  35000.0
2   Priya   21    Mumbai      NaN
3   Sneha   24  Kolhapur  40000.0
4    Amit   25    Nashik  45000.0
5   Kiran   22      Pune  38000.0
6   Rohit   23    Mumbai  35000.0
7   Pooja   24    Satara      NaN
8    Neha   21  Kolhapur  42000.0
9  Aditya   22    Satara  30000.0

DataFrame Info:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype  
---  ------  --------------  -----  
 0   Name    10 non-null     object 
 1   Age     10 non-null     int64  
 2   City    10 non-null     object 
 3   Salary  8 non-null      float64
dtypes: float64(1), int64(1), object(2)
memory usage: 452.0+ bytes

DataFrame Description:
             Age        Salary
count  10.000000      8.000000
mean   22.700000  36875.000000
std     1.337494   5409.977555
min    21.000000  30000.000000
25%    22.000000  33